---
- name: installing os centric piece first
  include: "os_family/{{ ansible_os_family }}.yml"

- name: instal python-cffi
  pip:
    name=cffi
    state=latest

- name: clone repository
  git:
    repo=https://github.com/g2p/bedup.git
    dest="{{ bedup.tmp }}"
    recursive=yes
    version="{{ bedup.ver }}"

- name: install bedup
  command: python3 setup.py install
    chdir="{{ bedup.tmp }}"

